[build]
  # ONLY build when these JSON files change
  # Returns exit 0 (skip build) if these files haven't changed
  # Returns exit 1 (do build) if any of these files have changed
  # This prevents image uploads from triggering deployments
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- public/content.json public/products.json public/category-visibility.json public/main-products.json public/products-*.json"

# Optional: Set Node version
[build.environment]
  NODE_VERSION = "18"

# Enable Netlify Functions
[functions]
  directory = "netlify/functions"